site_name: Paper Notes
docs_dir: ..
site_dir: ../../_site
theme:
  name: material
nav:
  - Home: README.md
  - Notes:
      - 2025-smith-multiagent-x: notes/2025-smith-multiagent-x.md
  - Tags:
      - RLHF: tags/rlhf.md
